name: Build on windows
on:
  release:
    types: [published]
jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Build app for release
        run: msbuild EIDCredentialProvider.sln -t:rebuild -property:Configuration=Release /p:Platform=x64

      - name: Install NSIS
        run: choco install nsis -y

      - name: Copy license for NSIS
        run: Copy-Item LICENSE Installer\License.txt

      - name: Create nsis installer
        run: '"C:\Program Files (x86)\NSIS\makensis.exe" /V3 "Installer\Installerx64.nsi"'

      - name: Create release archive
        shell: pwsh
        run: |
          $zipDir = New-Item -ItemType Directory -Path "Installer\Zip" -Force
          Copy-Item "Installer\EIDInstallx64.exe" -Destination $zipDir
          Copy-Item "Installer\License.txt" -Destination $zipDir
          Compress-Archive -Path "$($zipDir.FullName)\*" -DestinationPath "Installer\EIDAuthentication-x64.zip" -Force

      - name: upload binaries to release
        uses: softprops/action-gh-release@v2
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
            files: |
              Installer/EIDInstallx64.exe
              Installer/EIDAuthentication-x64.zip
