name: Build on windows.
on:
  release:
    types: [published]
jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Download CPDK 
        run: Invoke-WebRequest https://download.microsoft.com/download/1/7/6/176909b0-50f2-4df3-b29b-830a17ea7e38/CPDK_RELEASE_UPDATE/cpdksetup.exe -OutFile cpdksetup.exe

      - name: Unattened install of CPDK
        run: Start-Process -FilePath "./cpdksetup.exe" -Wait -NoNewWindow -ArgumentList "/features", "+", "/q", "/log", "./install-log.txt"

      - name: CPDK Check
        run: type ./install-log.txt; dir 'c:\program files (x86)\windows kits\10\'

      - name: Build app for release
        run: msbuild EIDCredentialProvider.sln -t:rebuild -property:Configuration=Release /p:Platform=x64

      - name: Install NSIS
        run: choco install nsis -y

      - name: Copy license for NSIS
        run: Copy-Item LICENSE Installer\License.txt

      - name: Verify build outputs
        run: Get-ChildItem -Path x64\Release -Recurse

      - name: Create nsis installer
        run: '"C:\Program Files (x86)\NSIS\makensis.exe" /V3 "Installer\Installerx64.nsi"'

      - name: upload binaries to release
        uses: softprops/action-gh-release@v2
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
            files: Installer/EIDInstallx64.exe